[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  https://github.com/mikalhart/TinyGPSPlus.git
  https://github.com/sparkfun/SparkFun_Ublox_Arduino_Library.git
  https://github.com/asukiaaa/MPU9250_asukiaaa.git
